config/routes.rb
# rubocop:disable Style/StringLiterals
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "pets", to: "pets#index"
  get "pets/new", to: "pets#new"
  get "pets/:id", to: "pets#show", as: "pet"
  post "pets", to: "pets#create"
  delete "pets/:id", to: "pets#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w[dog cat bird fish]

  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }

  def found_days_ago
    return nil unless found_on
    (Date.today - found_on).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrepLostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/index.html.erb
<div class="container">
  <h1 class="my-3" >Lost Pet's 🐶</h1>

  <ul>
    <% @pets.each do |pet| %>
      <li> <%= link_to  pet.name, pet_path(pet) %>  .  Found <%= pet.found_days_ago %> days ago.</li>
    <% end %>
  </ul>

  <%= link_to  "Register new lost pet",  pets_new_path %>
</div>

app/views/pets/new.html.erb
<h1>Register new lost pet</h1>

<%= form_with model: @pet do |f| %>
  <%= f.text_field :name %>
  <%= f.select :species, collection: Pet::SPECIES %>
  <%= f.text_field :address %>
  <%= f.date_select :found_on %>
  <%= f.submit %>
<% end %>

app/views/pets/show.html.erb
<h1><%= @pet.name.capitalize %> profile</h1>

<h3><bold>Species: </bold> <%= @pet.species.capitalize %>  </h3>
<h3><bold>Address: </bold> <%= @pet.address %>  </h3>
<h3><bold>Found on: </bold> <%= @pet.found_on %>  (<%= @pet.found_days_ago %> days ago) </h3>

<%= link_to  "Back to Lost Pets", pets_path %>
<%= link_to  "Delete Pet", pet_path(@pet), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>